In [5]:
import numpy as np
import pandas as pd

In [6]:
df_3 = pd.read_csv("cleaned/olist_order_items_dataset_cleaned.csv")

In [12]:
df_3.head(10)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,13:57:51,199.90,18.14
5,00048cc3ae777c65dbb7d2a0634bc1ea,1,ef92defde845ab8450f9d70c526ef70f,6426d21aca402a131fc0a5d0960a3c90,03:55:27,21.90,12.69
6,00054e8431b9d7675808bcb819fb4a32,1,8d4f2bb7e93e6710a28f34fa83ee7d28,7040e82f899a04d1b434b795a43b4617,12:10:31,19.90,11.85
7,000576fe39319847cbb9d288c5617fa6,1,557d850972a7d6f792fd18ae1400d9b6,5996cddab893a4652a15592fb58ab8db,12:30:45,810.00,70.75
8,0005a1a1728c9d785b8e2b08b904576c,1,310ae3c140ff94b03219ad0adc3c778f,a416b6a846a11724393025641d4edd5e,18:31:29,145.95,11.65
9,0005f50442cb953dcd1d21e1fb923495,1,4535b0e1091c278dfd193e5a1d63b39f,ba143b05f0110f0dc71ad71b4466ce92,14:10:56,53.99,11.40

In [9]:
Q1 = df_3["price"].quantile(0.25)
Q3 = df_3["price"].quantile(0.75)

IQR = Q3 - Q1
lower_fence = Q1 - 1.5 * IQR
upper_fence = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Fence:", lower_fence)
print("Upper Fence:", upper_fence)

Q1: 39.9
Q3: 134.9
IQR: 95.0
Lower Fence: -102.6
Upper Fence: 277.4

In [11]:
iqr_outliers = df_3[
    (df_3["price"] < lower_fence) |
    (df_3["price"] > upper_fence)
]

iqr_outliers[
    ["order_id", "price"]
]

                                order_id   price
7       000576fe39319847cbb9d288c5617fa6  810.00
16      0009c9a17f916a706d71784483a5d643  639.00
26      0011d82c4b53e22e84023405fb467e57  289.00
30      00137e170939bba5a3134e2386413108  397.00
39      0017afd5076e074a48f1f1a4c7bac9c5  809.10
...                                  ...     ...
112586  ffdc5e3279114c523a09296f8fd28331  299.99
112592  ffde92ba447b33a47d1c04d203f10f41  278.00
112632  fff7c4452f050315db1b3f24d9df5fcd  736.00
112645  fffc94f6ce00a00581880bf54a75a037  299.99
112646  fffcd46ef2263f404302a634eb57f7eb  350.00

[8427 rows x 2 columns]

In [14]:
df_6 = pd.read_csv("cleaned/olist_orders_dataset_cleaned.csv")

In [15]:
df_6.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_customer_date,order_estimated_delivery_date,order_purchase_Time,order_purchase_Date,order_approved_at_Time,order_approved_at_Date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-10 21:25:13,2017-10-18,10:56:33,2017-10-02,11:07:15,2017-10-02
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-08-07 15:27:45,2018-08-13,20:41:37,2018-07-24,03:24:27,2018-07-26
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-17 18:06:29,2018-09-04,08:38:49,2018-08-08,08:55:23,2018-08-08
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-12-02 00:28:42,2017-12-15,19:28:06,2017-11-18,19:45:59,2017-11-18
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-16 18:17:02,2018-02-26,21:18:39,2018-02-13,22:20:29,2018-02-13

In [16]:
df_6 = df_6.drop(columns =["order_purchase_timestamp", "order_approved_at"])

In [17]:
df_6.head()

,order_id,customer_id,order_status,order_delivered_customer_date,order_estimated_delivery_date,order_purchase_Time,order_purchase_Date,order_approved_at_Time,order_approved_at_Date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-10 21:25:13,2017-10-18,10:56:33,2017-10-02,11:07:15,2017-10-02
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-08-07 15:27:45,2018-08-13,20:41:37,2018-07-24,03:24:27,2018-07-26
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-17 18:06:29,2018-09-04,08:38:49,2018-08-08,08:55:23,2018-08-08
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-12-02 00:28:42,2017-12-15,19:28:06,2017-11-18,19:45:59,2017-11-18
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-16 18:17:02,2018-02-26,21:18:39,2018-02-13,22:20:29,2018-02-13

In [27]:
df_6["order_delivered_customer_date"] = pd.to_datetime(df_6["order_delivered_customer_date"])
df_6["order_delivered_customer_date"]

0       2017-10-10
1       2018-08-07
2       2018-08-17
3       2017-12-02
4       2018-02-16
           ...
99436   2017-03-17
99437   2018-02-28
99438   2017-09-21
99439   2018-01-25
99440   2018-03-16
Name: order_delivered_customer_date, Length: 99441, dtype: datetime64[ns]

In [19]:
df_6["order_delivered_customer_time"] =pd.to_datetime(df_6["order_delivered_customer_date"]).dt.time

In [23]:
df_6["order_delivered_customer_date"] = pd.to_datetime(df_6["order_delivered_customer_date"]).dt.date

In [21]:
df_6.head()

,order_id,customer_id,order_status,order_delivered_customer_date,order_estimated_delivery_date,order_purchase_Time,order_purchase_Date,order_approved_at_Time,order_approved_at_Date,order_delivered_customer_time
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-10,2017-10-18,10:56:33,2017-10-02,11:07:15,2017-10-02,00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-08-07,2018-08-13,20:41:37,2018-07-24,03:24:27,2018-07-26,00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-17,2018-09-04,08:38:49,2018-08-08,08:55:23,2018-08-08,00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-12-02,2017-12-15,19:28:06,2017-11-18,19:45:59,2017-11-18,00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-16,2018-02-26,21:18:39,2018-02-13,22:20:29,2018-02-13,00:00:00

In [29]:
df_6.to_csv("cleaned/olist_orders_dataset_cleaned2.csv")