In [1]:
! pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\admin\appdata\local\programs\python\python310\lib\site-packages (26.7.0)

In [2]:
import mysql.connector
print("done")

done

In [3]:
conn = mysql.connector.connect(
    host = 'localhost',
    user = 'root',
    password = 'Jomix#11',
    database = 'cart2insights',
    use_pure = True
 )

cursor = conn.cursor()
print("connection is made successfully")

connection is made successfully

In [4]:
query = "use cart2insights"
cursor.execute(query)

In [7]:
create_geo_table = """
CREATE TABLE IF NOT EXISTS geolocation (
    geolocation_zip_code_prefix CHAR(5),
    geolocation_lat DECIMAL(10, 8),
    geolocation_lng DECIMAL(11, 8),
    geolocation_city VARCHAR(100),
    geolocation_state CHAR(2)
)
"""

cursor.execute(create_geo_table)
conn.commit()

print("Geolocation table created successfully.")

Geolocation table created successfully.

In [10]:
import pandas as pd

In [6]:
df_2 = pd.read_csv("cleaned/olist_geolocation_dataset_cleaned.csv")

In [7]:
df_2.columns

Index(['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng',
       'geolocation_city', 'geolocation_state'],
      dtype='object')

In [8]:
insert_query = """
INSERT INTO geolocation
(geolocation_zip_code_prefix, geolocation_lat, geolocation_lng,
       geolocation_city, geolocation_state)
VALUES (%s, %s, %s, %s, %s)
"""

In [9]:
for index, row in df_2.iterrows():

    values = (
        row["geolocation_zip_code_prefix"],
        row["geolocation_lat"],
        row["geolocation_lng"],
        row["geolocation_city"],
        row["geolocation_state"]
    )
    cursor.execute(insert_query, values)

    
conn.commit()
print("inserted successfully")

KeyboardInterrupt:

In [ ]:
conn.commit
print("inserted successfully")

In [12]:

df_3 = pd.read_csv("cleaned/olist_order_items_dataset_cleaned.csv")

In [178]:
df_3.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,13:57:51,199.90,18.14

In [194]:
print(df_3["freight_value"].max())
print(df_3["freight_value"].min())
print(df_3["freight_value"].head())

409.68
0.0
0    13.29
1    19.93
2    17.87
3    12.79
4    18.14
Name: freight_value, dtype: float64

In [199]:
create_table_query = """
CREATE TABLE IF NOT EXISTS orders (
    order_id VARCHAR(50),
    order_item_id INT,
    product_id VARCHAR(50) NOT NULL,
    seller_id  VARCHAR(50) NOT NULL,
    shipping_limit_date TIME,
    price DECIMAL(10,2),
    freight_value DECIMAL(10,2)

    )
"""

cursor.execute(create_table_query)

print("Table created successfully")

Table created successfully

In [200]:
insert_query = """
INSERT INTO orders
(order_id, order_item_id, product_id,
       seller_id, shipping_limit_date, price, freight_value)
VALUES (%s, %s, %s, %s, %s, %s, %s)
"""

In [201]:
for index, row in df_3.iterrows():

    values = (
        row["order_id"],
        row["order_item_id"],
        row["product_id"],
        row["seller_id"], 
        row["shipping_limit_date"],
        row["price"],
        row["freight_value"]
    )
    cursor.execute(insert_query, values)

    
conn.commit()
print("inserted successfully")

inserted successfully

In [50]:
df_4 = pd.read_csv("cleaned/olist_order_payments_dataset_cleaned.csv")

In [51]:
df_4.columns

Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='object')

In [ ]:
create_table_query = """
CREATE TABLE IF NOT EXISTS payment (
    order_id VARCHAR(50),
    payment_sequential INT,
    payment_type VARCHAR(50),
    payment_installments  INT,
    payment_value INT
)
"""

cursor.execute(create_table_query)

print("Table created successfully")

Table created successfully

In [68]:
insert_query = """
INSERT INTO payment
(order_id, payment_sequential, payment_type,
       payment_installments, payment_value)
VALUES (%s, %s, %s, %s, %s)
"""

In [69]:
for index, row in df_4.iterrows():

    values = (
        row["order_id"],
        row["payment_sequential"],
        row["payment_type"],
        row["payment_installments"],
        row["payment_value"],
        
    )
    cursor.execute(insert_query, values)

    
conn.commit()
print("inserted successfully")

inserted successfully

In [58]:
df_4.duplicated().sum()

np.int64(0)

In [70]:
df_5 = pd.read_csv("cleaned/olist_order_reviews_dataset_cleaned.csv")

In [73]:
df_5.head()

,Unnamed: 0,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_Time,review_answer_date
0,0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,Recomendo,Muito bom,2018-01-18 00:00:00,21:46:59,2018-01-18
1,1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,Recomendo,Muito bom,2018-03-10 00:00:00,03:05:13,2018-03-11
2,2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,Recomendo,Muito bom,2018-02-17 00:00:00,14:36:24,2018-02-18
3,3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,Recomendo,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,22:02:06,2017-04-21
4,4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,Recomendo,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,10:26:53,2018-03-02

In [81]:
df_5 = df_5.drop(columns=["Unnamed: 0"])

In [114]:
df_5.dtypes

review_id                 object
order_id                  object
review_score               int64
review_comment_title      object
review_comment_message    object
review_creation_date      object
review_answer_Time        object
review_answer_date        object
dtype: object

In [131]:
create_table_query = """
CREATE TABLE IF NOT EXISTS review (
    review_id VARCHAR(100),
    order_id VARCHAR(50),
    review_score INT,
    review_comment_title TEXT,
    review_comment_message TEXT,
    review_creation_date DATETIME,
    review_answer_Time TIME,
    review_answer_date DATETIME
    )
"""

cursor.execute(create_table_query)

print("Table created successfully")

Table created successfully

In [132]:
insert_query = """
INSERT INTO review
(review_id, order_id, review_score, review_comment_title, review_comment_message, review_creation_date,
       review_answer_Time, review_answer_date)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
"""

In [133]:
for index, row in df_5.iterrows():

    values = (
        row["review_id"],
        row["order_id"],
        row["review_score"],
        row["review_comment_title"],
        row["review_comment_message"],
        row["review_creation_date"],
        row["review_answer_Time"],
        row["review_answer_date"]       
    )
    cursor.execute(insert_query, values)

    
conn.commit()
print("inserted successfully")

inserted successfully

In [135]:
df_6 = pd.read_csv("cleaned/olist_orders_dataset_cleaned.csv")

In [136]:
df_6.columns

Index(['Unnamed: 0', 'order_id', 'customer_id', 'order_status',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_purchase_Time', 'order_purchase_Date', 'order_approved_at_Time',
       'order_approved_at_Date', 'order_delivered_customer_time'],
      dtype='object')

In [137]:
df_6.dtypes

Unnamed: 0                        int64
order_id                         object
customer_id                      object
order_status                     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
order_purchase_Time              object
order_purchase_Date              object
order_approved_at_Time           object
order_approved_at_Date           object
order_delivered_customer_time    object
dtype: object

In [140]:
df_6 = df_6.drop(columns=["Unnamed: 0"])

In [141]:
df_6.columns

Index(['order_id', 'customer_id', 'order_status',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_purchase_Time', 'order_purchase_Date', 'order_approved_at_Time',
       'order_approved_at_Date', 'order_delivered_customer_time'],
      dtype='object')

In [142]:
create_table_query = """
CREATE TABLE IF NOT EXISTS orders_del (
    order_id VARCHAR(100),
    customer_id VARCHAR(50),
    order_status VARCHAR(50),
    order_delivered_customer_date DATE,
    order_estimated_delivery_date DATE,
    order_purchase_Time TIME,
    order_purchase_Date DATE,
    order_approved_at_Time TIME,
    order_approved_at_Date DATE,
    order_delivered_customer_time TIME    
    )
"""

cursor.execute(create_table_query)

print("Table created successfully")

Table created successfully

In [143]:
insert_query = """
INSERT INTO orders_del
(order_id, customer_id, order_status, order_delivered_customer_date, order_estimated_delivery_date, order_purchase_Time,
       order_purchase_Date, order_approved_at_Time, order_approved_at_Date, order_delivered_customer_time)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

In [145]:
for index, row in df_6           .iterrows():

    values = (
        row["order_id"],
        row["customer_id"],
        row["order_status"],
        row["order_delivered_customer_date"],
        row["order_estimated_delivery_date"],
        row["order_purchase_Time"],
        row["order_purchase_Date"],
        row["order_approved_at_Time"],
        row["order_approved_at_Date"],
        row["order_delivered_customer_time"]
    )
    cursor.execute(insert_query, values)

    
conn.commit()
print("inserted successfully")

inserted successfully

In [146]:
df_7 = pd.read_csv("cleaned/olist_products_dataset_cleaned.csv")

In [148]:
df_7.columns

Index(['Unnamed: 0', 'product_id', 'product_category_name',
       'product_photos_qty', 'product_weight_g', 'product_length_cm',
       'product_height_cm', 'product_width_cm'],
      dtype='object')

In [149]:
df_7 = df_7.drop(columns=["Unnamed: 0"])

In [151]:
df_7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   product_id             32951 non-null  object
 1   product_category_name  32341 non-null  object
 2   product_photos_qty     32341 non-null  float64
 3   product_weight_g       32949 non-null  float64
 4   product_length_cm      32949 non-null  float64
 5   product_height_cm      32949 non-null  float64
 6   product_width_cm       32949 non-null  float64
dtypes: float64(5), object(2)
memory usage: 1.8+ MB

In [150]:
df_7.columns

Index(['product_id', 'product_category_name', 'product_photos_qty',
       'product_weight_g', 'product_length_cm', 'product_height_cm',
       'product_width_cm'],
      dtype='object')

In [148]:
create_table_query = """
CREATE TABLE IF NOT EXISTS product (
    product_id VARCHAR(100),
    product_category_name VARCHAR(50),
    product_photos_qty INT,
    product_weight_g DECIMAL(10.2),
    product_length_cm DECIMAL(10.2),
    product_height_cm DECIMAL(10.2),
    product_width_cm  DECIMAL(10.2),
    PRIMARY KEY (product_id)
    )
"""

cursor.execute(create_table_query)

print("Table created successfully")

Table created successfully

In [149]:
insert_query = """
INSERT INTO product
(product_id, product_category_name, product_photos_qty, product_weight_g, product_length_cm, product_height_cm,
       product_width_cm)
VALUES (%s, %s, %s, %s, %s, %s, %s)
"""

In [150]:
for index, row in df_7.iterrows():

    values = (
        row["product_id"],
        row["product_category_name"],
        row["product_photos_qty"],
        row["product_weight_g"],
        row["product_length_cm"],
        row["product_height_cm"],
        row["product_width_cm"]
        
    )
    cursor.execute(insert_query, values)

    
conn.commit()
print("inserted successfully")

ProgrammingError: Failed processing format-parameters; Python 'natype' cannot be converted to a MySQL type

In [157]:
df_8 = pd.read_csv("cleaned/olist_sellers_dataset_cleaned.csv")

In [159]:
df_8.columns

Index(['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state'], dtype='object')

In [161]:
create_table_query = """
CREATE TABLE IF NOT EXISTS sellers (
    seller_id VARCHAR(100),
    seller_zip_code_prefix INT,
    seller_city VARCHAR(50),
    seller_state VARCHAR(50),
    PRIMARY KEY (seller_id)
    )
"""

cursor.execute(create_table_query)

print("Table created successfully")

Table created successfully

In [162]:
insert_query = """
INSERT INTO sellers
(seller_id, seller_zip_code_prefix, seller_city, seller_state)
VALUES (%s, %s, %s, %s)
"""

In [163]:
for index, row in df_8.iterrows():

    values = (
        row["seller_id"],
        row["seller_zip_code_prefix"],
        row["seller_city"],
        row["seller_state"],
                
    )
    cursor.execute(insert_query, values)

    
conn.commit()
print("inserted successfully")

inserted successfully

In [165]:
df_9 = pd.read_csv("cleaned/product_category_name_translation_cleaned.csv")

In [166]:
df_9.columns

Index(['product_category_name', 'product_category_name_english'], dtype='object')

In [167]:
create_table_query = """
CREATE TABLE IF NOT EXISTS product_det (
    product_category_name VARCHAR(100),
    product_category_name_english VARCHAR(50),
    PRIMARY KEY (product_category_name)
    )
"""

cursor.execute(create_table_query)

print("Table created successfully")

Table created successfully

In [168]:
insert_query = """
INSERT INTO product_det
(product_category_name, product_category_name_english)
VALUES (%s, %s)
"""

In [169]:
for index, row in df_9.iterrows():

    values = (
        row["product_category_name"],
        row["product_category_name_english"]               
    )
    cursor.execute(insert_query, values)

    
conn.commit()
print("inserted successfully")

inserted successfully

In [167]:
drop_tables = [
        "products"
   ]

for table in drop_tables:
    cursor.execute(f"DROP TABLE IF EXISTS {table}")

conn.commit()

print("Old SQL tables deleted successfully")

Old SQL tables deleted successfully

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv("cleaned/olist_customers_dataset_cleaned.csv")

In [7]:
df.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='object')

In [13]:
df["customer_id"] = df["customer_id"].astype("string")
df["customer_unique_id"] = df["customer_unique_id"].astype("string")
df["customer_zip_code_prefix"] = df["customer_zip_code_prefix"].astype("string")
df["customer_city"] = df["customer_city"].astype("string")
df["customer_state"] = df["customer_state"].astype("string")

df.dtypes

customer_id                 string[python]
customer_unique_id          string[python]
customer_zip_code_prefix    string[python]
customer_city               string[python]
customer_state              string[python]
dtype: object

In [16]:
create_table_query = """
CREATE TABLE IF NOT EXISTS customers (
    customer_id VARCHAR(50) PRIMARY KEY,
    customer_unique_id VARCHAR(50),
    customer_zip_code_prefix CHAR(5),
    customer_city VARCHAR(100),
    customer_state CHAR(2)
)
"""

cursor.execute(create_table_query)
conn.commit()

print("customers table created successfully")

customers table created successfully

In [17]:
insert_query = """
INSERT INTO customers
(customer_id, customer_unique_id, customer_zip_code_prefix, customer_city, customer_state)
VALUES (%s, %s, %s, %s, %s)
"""

for index, row in df.iterrows():
    values = (
        row["customer_id"],
        row["customer_unique_id"],
        row["customer_zip_code_prefix"],
        row["customer_city"],
        row["customer_state"]
    )
    cursor.execute(insert_query, values)

conn.commit()

print("Customers inserted successfully")

Customers inserted successfully

In [19]:
df_2 = pd.read_csv("cleaned/olist_geolocation_dataset_cleaned.csv")

In [20]:
df_2.columns

Index(['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng',
       'geolocation_city', 'geolocation_state'],
      dtype='object')

In [21]:
df_2["geolocation_zip_code_prefix"] = df_2["geolocation_zip_code_prefix"].astype("string")
df_2["geolocation_lat"] = pd.to_numeric(df_2["geolocation_lat"], errors="coerce")
df_2["geolocation_lng"] = pd.to_numeric(df_2["geolocation_lng"], errors="coerce")
df_2["geolocation_city"] = df_2["geolocation_city"].astype("string")
df_2["geolocation_state"] = df_2["geolocation_state"].astype("string")

df_2.dtypes

geolocation_zip_code_prefix    string[python]
geolocation_lat                       float64
geolocation_lng                       float64
geolocation_city               string[python]
geolocation_state              string[python]
dtype: object

In [23]:
create_table_query = """
CREATE TABLE IF NOT EXISTS geolocation (
    geolocation_zip_code_prefix CHAR(5),
    geolocation_lat DECIMAL(10,8),
    geolocation_lng DECIMAL(11,8),
    geolocation_city VARCHAR(100),
    geolocation_state CHAR(2)
)
"""

cursor.execute(create_table_query)
conn.commit()

print("geolocation table created successfully")

geolocation table created successfully

In [31]:
insert_query = """
INSERT INTO geolocation
(geolocation_zip_code_prefix, geolocation_lat, geolocation_lng, geolocation_city, geolocation_state)
VALUES (%s, %s, %s, %s, %s)
"""

for index, row in df_2.iterrows():
    values = (
        row["geolocation_zip_code_prefix"],
        row["geolocation_lat"],
        row["geolocation_lng"],
        row["geolocation_city"],
        row["geolocation_state"]
    )
    cursor.execute(insert_query, values)

conn.commit()

print("Geolocation data inserted successfully")

KeyboardInterrupt:

In [168]:
df_7 = pd.read_csv("cleaned/olist_products_dataset_cleaned.csv")

In [169]:
df_7= df_7.drop(columns=["Unnamed: 0"])

In [170]:
df_7.columns

Index(['product_id', 'product_category_name', 'product_photos_qty',
       'product_weight_g', 'product_length_cm', 'product_height_cm',
       'product_width_cm'],
      dtype='object')

In [171]:
df_7["product_id"] = df_7["product_id"].astype("string")
df_7["product_category_name"] = df_7["product_category_name"].astype("string")
df_7["product_photos_qty"] = pd.to_numeric(df_7["product_photos_qty"], errors="coerce").astype("Int64")
df_7["product_weight_g"] = pd.to_numeric(df_7["product_weight_g"], errors="coerce")
df_7["product_length_cm"] = pd.to_numeric(df_7["product_length_cm"], errors="coerce")
df_7["product_height_cm"] = pd.to_numeric(df_7["product_height_cm"], errors="coerce")
df_7["product_width_cm"] = pd.to_numeric(df_7["product_width_cm"], errors="coerce")

df_7.dtypes

product_id               string[python]
product_category_name    string[python]
product_photos_qty                Int64
product_weight_g                float64
product_length_cm               float64
product_height_cm               float64
product_width_cm                float64
dtype: object

In [172]:
df_7 = df_7.astype(object)
df_7 = df_7.where(df_7.notna(), None)

In [173]:
create_table_query = """
CREATE TABLE IF NOT EXISTS products (
    product_id VARCHAR(50) PRIMARY KEY,
    product_category_name VARCHAR(100),
    product_photos_qty INT,
    product_weight_g DECIMAL(10,2),
    product_length_cm DECIMAL(10,2),
    product_height_cm DECIMAL(10,2),
    product_width_cm DECIMAL(10,2)
)
"""

cursor.execute(create_table_query)
conn.commit()

print("products table created successfully")

products table created successfully

In [ ]:
insert_query = """
INSERT INTO products 
(product_id, product_category_name, product_photos_qty, product_weight_g,
 product_length_cm, product_height_cm, product_width_cm)
VALUES (%s, %s, %s, %s, %s, %s, %s)
"""

for index, row in df_7.iterrows():
    values = (
        row["product_id"],
        row["product_category_name"],
        row["product_photos_qty"],
        row["product_weight_g"],
        row["product_length_cm"],
        row["product_height_cm"],
        row["product_width_cm"]
    )
    cursor.execute(insert_query, values)

conn.commit()

print("Products inserted successfully")

Products inserted successfully

In [18]:
df_8 = pd.read_csv("cleaned/olist_sellers_dataset_cleaned.csv")

In [19]:
df_8.columns

Index(['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state'], dtype='object')

In [22]:
df_8["seller_id"] = df_8["seller_id"].astype("string")
df_8["seller_zip_code_prefix"] = df_8["seller_zip_code_prefix"].astype("string")
df_8["seller_city"] = df_8["seller_city"].astype("string")
df_8["seller_state"] = df_8["seller_state"].astype("string")

df_8.dtypes

seller_id                 string[python]
seller_zip_code_prefix    string[python]
seller_city               string[python]
seller_state              string[python]
dtype: object

In [23]:
create_table_query = """
CREATE TABLE IF NOT EXISTS sellers (
    seller_id VARCHAR(50) PRIMARY KEY,
    seller_zip_code_prefix CHAR(5),
    seller_city VARCHAR(100),
    seller_state CHAR(2)
)
"""

cursor.execute(create_table_query)
conn.commit()

print("sellers table created successfully")

sellers table created successfully

In [25]:
insert_query = """
INSERT INTO sellers
(seller_id, seller_zip_code_prefix, seller_city, seller_state)
VALUES (%s, %s, %s, %s)
"""

for index, row in df_8.iterrows():
    values = (
        row["seller_id"],
        row["seller_zip_code_prefix"],
        row["seller_city"],
        row["seller_state"]
    )
    cursor.execute(insert_query, values)

conn.commit()

print("Sellers inserted successfully")

Sellers inserted successfully

In [26]:
df_9 = pd.read_csv("cleaned/product_category_name_translation_cleaned.csv")

In [27]:
df_9.columns

Index(['product_category_name', 'product_category_name_english'], dtype='object')

In [28]:
df_9["product_category_name"] = df_9["product_category_name"].astype("string")
df_9["product_category_name_english"] = df_9["product_category_name_english"].astype("string")

df_9.dtypes

product_category_name            string[python]
product_category_name_english    string[python]
dtype: object

In [29]:
create_table_query = """
CREATE TABLE IF NOT EXISTS product_category_translation (
    product_category_name VARCHAR(100) PRIMARY KEY,
    product_category_name_english VARCHAR(100)
)
"""

cursor.execute(create_table_query)
conn.commit()

print("product_category_translation table created successfully")

product_category_translation table created successfully

In [30]:
insert_query = """
INSERT INTO product_category_translation
(product_category_name, product_category_name_english)
VALUES (%s, %s)
"""

for index, row in df_9.iterrows():
    values = (
        row["product_category_name"],
        row["product_category_name_english"]
    )
    cursor.execute(insert_query, values)

conn.commit()

print("Product category translation inserted successfully")

Product category translation inserted successfully

In [31]:
df_3 = pd.read_csv("cleaned/olist_order_items_dataset_cleaned.csv")

In [32]:
df_3.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='object')

In [33]:
df_6 = pd.read_csv("cleaned/olist_orders_dataset_cleaned.csv")

In [67]:
df_3 = pd.read_csv("cleaned/olist_order_items_dataset_cleaned.csv")

In [68]:
df_3.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='object')

In [69]:
df_3["order_id"] = df_3["order_id"].astype("string")
df_3["order_item_id"] = pd.to_numeric(df_3["order_item_id"], errors="coerce").astype("Int64")
df_3["product_id"] = df_3["product_id"].astype("string")
df_3["seller_id"] = df_3["seller_id"].astype("string")
df_3["shipping_limit_date"] = pd.to_datetime(df_3["shipping_limit_date"], errors="coerce")
df_3["price"] = pd.to_numeric(df_3["price"], errors="coerce")
df_3["freight_value"] = pd.to_numeric(df_3["freight_value"], errors="coerce")

df_3.dtypes

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_8076\3779460614.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_3["shipping_limit_date"] = pd.to_datetime(df_3["shipping_limit_date"], errors="coerce")

order_id               string[python]
order_item_id                   Int64
product_id             string[python]
seller_id              string[python]
shipping_limit_date    datetime64[ns]
price                         float64
freight_value                 float64
dtype: object

In [70]:
create_table_query = """
CREATE TABLE IF NOT EXISTS order_items (
    order_id VARCHAR(50),
    order_item_id INT,
    product_id VARCHAR(50),
    seller_id VARCHAR(50),
    shipping_limit_date DATETIME,
    price DECIMAL(10,2),
    freight_value DECIMAL(10,2),
    PRIMARY KEY (order_id, order_item_id)
)
"""

cursor.execute(create_table_query)
conn.commit()

print("order_items table created successfully")

order_items table created successfully

In [71]:
insert_query = """
INSERT INTO order_items
(order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value)
VALUES (%s, %s, %s, %s, %s, %s, %s)
"""

for index, row in df_3.iterrows():
    values = (
        row["order_id"],
        row["order_item_id"],
        row["product_id"],
        row["seller_id"],
        row["shipping_limit_date"],
        row["price"],
        row["freight_value"]
    )
    cursor.execute(insert_query, values)

conn.commit()

print("Order items inserted successfully")

Order items inserted successfully

In [72]:
df_4 = pd.read_csv("cleaned/olist_order_payments_dataset_cleaned.csv")

In [73]:
df_4.columns

Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='object')

In [74]:
df_4["order_id"] = df_4["order_id"].astype("string")
df_4["payment_sequential"] = pd.to_numeric(df_4["payment_sequential"], errors="coerce").astype("Int64")
df_4["payment_type"] = df_4["payment_type"].astype("string")
df_4["payment_installments"] = pd.to_numeric(df_4["payment_installments"], errors="coerce").astype("Int64")
df_4["payment_value"] = pd.to_numeric(df_4["payment_value"], errors="coerce")

df_4.dtypes

order_id                string[python]
payment_sequential               Int64
payment_type            string[python]
payment_installments             Int64
payment_value                  float64
dtype: object

In [75]:
create_table_query = """
CREATE TABLE order_payments (
    order_id VARCHAR(50),
    payment_sequential INT,
    payment_type VARCHAR(50),
    payment_installments INT,
    payment_value DECIMAL(10,2),
    PRIMARY KEY (order_id, payment_sequential)
)
"""

cursor.execute(create_table_query)
conn.commit()

print("order_payments table created successfully")

order_payments table created successfully

In [76]:
insert_query = """
INSERT INTO order_payments
(order_id, payment_sequential, payment_type, payment_installments, payment_value)
VALUES (%s, %s, %s, %s, %s)
"""

for index, row in df_4.iterrows():
    values = (
        row["order_id"],
        row["payment_sequential"],
        row["payment_type"],
        row["payment_installments"],
        row["payment_value"]
    )
    cursor.execute(insert_query, values)

conn.commit()

print("Order payments inserted successfully")

Order payments inserted successfully

In [77]:
df_5 = pd.read_csv("cleaned/olist_order_reviews_dataset_cleaned.csv")

In [78]:
df_5.columns

Index(['Unnamed: 0', 'review_id', 'order_id', 'review_score',
       'review_comment_title', 'review_comment_message',
       'review_creation_date', 'review_answer_Time', 'review_answer_date'],
      dtype='object')